// -------------------------------------------------------------
// 
// File Name: C:\Users\iande\Desktop\covg_fpga_project\covg_fpga\Matlab\DSPfilterFunctions\CMDFilters\codegen\sumGain\hdlsrc\sumGain_fixpt.v
// Created: 2021-08-12 13:10:32
// 
// Generated by MATLAB 9.9, MATLAB Coder 5.1 and HDL Coder 3.17
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sumGain_fixpt
// Source Path: sumGain_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sumGain_fixpt
          (in1,
           in2,
           in3,
           g1,
           g2,
           g3,
           scaleVal,
           y);


  input   signed [13:0] in1;  // sfix14_En13
  input   signed [13:0] in2;  // sfix14_En13
  input   signed [13:0] in3;  // sfix14_En13
  input   [7:0] g1;  // ufix8
  input   [7:0] g2;  // ufix8
  input   [7:0] g3;  // ufix8
  input   [7:0] scaleVal;  // ufix8
  output  signed [13:0] y;  // sfix14_En13


  reg signed [13:0] y_1;  // sfix14_En13
  reg [9:0] sumGain_fixpt_gtotal;  // ufix10
  reg [41:0] sumGain_fixpt_tmp;  // ufix42_En24
  reg [41:0] sumGain_fixpt_tmp_0;  // ufix42_En24
  reg [41:0] sumGain_fixpt_tmp_1;  // ufix42_En24
  reg signed [57:0] sumGain_fixpt_y1;  // sfix58_En37
  reg signed [65:0] sumGain_fixpt_tmp_2;  // sfix66_En37
  reg [31:0] sumGain_fixpt_div_temp;  // ufix32_En24
  reg [31:0] sumGain_fixpt_div_temp_0;  // ufix32_En24
  reg [31:0] sumGain_fixpt_div_temp_1;  // ufix32_En24
  reg signed [57:0] sumGain_fixpt_div_temp_2;  // sfix58_En37
  reg [8:0] sumGain_fixpt_add_temp;  // ufix9
  reg [31:0] sumGain_fixpt_cast;  // ufix32_En24
  reg [31:0] sumGain_fixpt_cast_0;  // ufix32_En24
  reg [31:0] sumGain_fixpt_cast_1;  // ufix32_En24
  reg signed [42:0] sumGain_fixpt_cast_2;  // sfix43_En24
  reg signed [56:0] sumGain_fixpt_mul_temp;  // sfix57_En37
  reg signed [55:0] sumGain_fixpt_add_cast;  // sfix56_En37
  reg signed [56:0] sumGain_fixpt_add_cast_0;  // sfix57_En37
  reg signed [42:0] sumGain_fixpt_cast_3;  // sfix43_En24
  reg signed [56:0] sumGain_fixpt_mul_temp_0;  // sfix57_En37
  reg signed [55:0] sumGain_fixpt_add_cast_1;  // sfix56_En37
  reg signed [56:0] sumGain_fixpt_add_cast_2;  // sfix57_En37
  reg signed [56:0] sumGain_fixpt_add_temp_0;  // sfix57_En37
  reg signed [57:0] sumGain_fixpt_add_cast_3;  // sfix58_En37
  reg signed [42:0] sumGain_fixpt_cast_4;  // sfix43_En24
  reg signed [56:0] sumGain_fixpt_mul_temp_1;  // sfix57_En37
  reg signed [55:0] sumGain_fixpt_add_cast_4;  // sfix56_En37
  reg signed [57:0] sumGain_fixpt_add_cast_5;  // sfix58_En37
  reg signed [8:0] sumGain_fixpt_slice_cast;  // sfix9
  reg signed [57:0] sumGain_fixpt_y1_0;  // sfix58_En37
  reg signed [8:0] sumGain_fixpt_cast_5;  // sfix9
  reg [9:0] sumGain_fixpt_t_0;  // ufix10
  reg [9:0] sumGain_fixpt_t_1;  // ufix10
  reg signed [8:0] sumGain_fixpt_t_2;  // sfix9
  reg [8:0] sumGain_fixpt_t_3;  // ufix9
  reg [8:0] sumGain_fixpt_t_4;  // ufix9


  always @(g1, g2, g3, in1, in2, in3, scaleVal) begin
    sumGain_fixpt_div_temp = 32'b00000000000000000000000000000000;
    sumGain_fixpt_div_temp_0 = 32'b00000000000000000000000000000000;
    sumGain_fixpt_div_temp_1 = 32'b00000000000000000000000000000000;
    sumGain_fixpt_div_temp_2 = 58'sh000000000000000;
    sumGain_fixpt_y1_0 = 58'sh000000000000000;
    sumGain_fixpt_cast = 32'b00000000000000000000000000000000;
    sumGain_fixpt_cast_0 = 32'b00000000000000000000000000000000;
    sumGain_fixpt_cast_1 = 32'b00000000000000000000000000000000;
    sumGain_fixpt_slice_cast = 9'sb000000000;
    sumGain_fixpt_cast_5 = 9'sb000000000;
    sumGain_fixpt_t_2 = 9'sb000000000;
    //HDL code generation from MATLAB function: sumGain_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //           Generated by MATLAB 9.9 and Fixed-Point Designer 7.1           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //function to take in gains of the three CMD filters, and apply them to
    //filter outputs and scale the output back to 14 bits
    // gtype = numerictype([], 64, 32);
    // gtotal = fi('numerictype', gtype);
    // g1 = fi(g1,0, 32, 16);
    // g2 = fi(g2,0, 32, 16);
    // g3 = fi(g3,0, 32, 16);
    // scaleVal = fi(scaleVal, 0, 32, 0);
    //outputType = numerictype(1, 14, 13);
    // addType = numerictype(0, 34, 0);
    sumGain_fixpt_t_3 = {1'b0, g1};
    sumGain_fixpt_t_4 = {1'b0, g2};
    sumGain_fixpt_add_temp = sumGain_fixpt_t_3 + sumGain_fixpt_t_4;
    sumGain_fixpt_t_0 = {1'b0, sumGain_fixpt_add_temp};
    sumGain_fixpt_t_1 = {2'b0, g3};
    sumGain_fixpt_gtotal = sumGain_fixpt_t_0 + sumGain_fixpt_t_1;
    // gintermediate = add(addType, g1, g2);
    // gtotal = add(addType, gintermediate, g3);
    // out1 = fi(((g1/gtotal)*in1), 1, 14, 13);
    // out2 = fi(((g2/gtotal)*in2), 1, 14, 13);
    // out3 = fi(((g3/gtotal)*in3), 1, 14, 13);
    if (sumGain_fixpt_gtotal == 10'b0000000000) begin
      sumGain_fixpt_tmp = 42'h3FFFFFFFFFF;
    end
    else begin
      sumGain_fixpt_cast = {g1, 24'b000000000000000000000000};
      if (sumGain_fixpt_gtotal == 31'sd0) begin
        sumGain_fixpt_div_temp = 32'b11111111111111111111111111111111;
      end
      else begin
        sumGain_fixpt_div_temp = sumGain_fixpt_cast / sumGain_fixpt_gtotal;
      end
      sumGain_fixpt_tmp = {10'b0, sumGain_fixpt_div_temp};
    end
    if (sumGain_fixpt_gtotal == 10'b0000000000) begin
      sumGain_fixpt_tmp_0 = 42'h3FFFFFFFFFF;
    end
    else begin
      sumGain_fixpt_cast_0 = {g2, 24'b000000000000000000000000};
      if (sumGain_fixpt_gtotal == 31'sd0) begin
        sumGain_fixpt_div_temp_0 = 32'b11111111111111111111111111111111;
      end
      else begin
        sumGain_fixpt_div_temp_0 = sumGain_fixpt_cast_0 / sumGain_fixpt_gtotal;
      end
      sumGain_fixpt_tmp_0 = {10'b0, sumGain_fixpt_div_temp_0};
    end
    if (sumGain_fixpt_gtotal == 10'b0000000000) begin
      sumGain_fixpt_tmp_1 = 42'h3FFFFFFFFFF;
    end
    else begin
      sumGain_fixpt_cast_1 = {g3, 24'b000000000000000000000000};
      if (sumGain_fixpt_gtotal == 31'sd0) begin
        sumGain_fixpt_div_temp_1 = 32'b11111111111111111111111111111111;
      end
      else begin
        sumGain_fixpt_div_temp_1 = sumGain_fixpt_cast_1 / sumGain_fixpt_gtotal;
      end
      sumGain_fixpt_tmp_1 = {10'b0, sumGain_fixpt_div_temp_1};
    end
    // out1 = fi((divide(numerictype(1, 14, 13), g1, gtotal)*in1), 1, 14, 13);
    // out2 = fi((divide(numerictype(1, 14, 13), g2, gtotal)*in2), 1, 14, 13);
    // out3 = fi((divide(numerictype(1, 14, 13), g3, gtotal)*in3), 1, 14, 13);
    //y1 = fi((out1 + out2 + out3), 1, 14, 13);
    sumGain_fixpt_cast_2 = {1'b0, sumGain_fixpt_tmp};
    sumGain_fixpt_mul_temp = sumGain_fixpt_cast_2 * in1;
    if ((sumGain_fixpt_mul_temp[56] == 1'b0) && (sumGain_fixpt_mul_temp[55] != 1'b0)) begin
      sumGain_fixpt_add_cast = 56'sh7FFFFFFFFFFFFF;
    end
    else if ((sumGain_fixpt_mul_temp[56] == 1'b1) && (sumGain_fixpt_mul_temp[55] != 1'b1)) begin
      sumGain_fixpt_add_cast = 56'sh80000000000000;
    end
    else begin
      sumGain_fixpt_add_cast = sumGain_fixpt_mul_temp[55:0];
    end
    sumGain_fixpt_add_cast_0 = {sumGain_fixpt_add_cast[55], sumGain_fixpt_add_cast};
    sumGain_fixpt_cast_3 = {1'b0, sumGain_fixpt_tmp_0};
    sumGain_fixpt_mul_temp_0 = sumGain_fixpt_cast_3 * in2;
    if ((sumGain_fixpt_mul_temp_0[56] == 1'b0) && (sumGain_fixpt_mul_temp_0[55] != 1'b0)) begin
      sumGain_fixpt_add_cast_1 = 56'sh7FFFFFFFFFFFFF;
    end
    else if ((sumGain_fixpt_mul_temp_0[56] == 1'b1) && (sumGain_fixpt_mul_temp_0[55] != 1'b1)) begin
      sumGain_fixpt_add_cast_1 = 56'sh80000000000000;
    end
    else begin
      sumGain_fixpt_add_cast_1 = sumGain_fixpt_mul_temp_0[55:0];
    end
    sumGain_fixpt_add_cast_2 = {sumGain_fixpt_add_cast_1[55], sumGain_fixpt_add_cast_1};
    sumGain_fixpt_add_temp_0 = sumGain_fixpt_add_cast_0 + sumGain_fixpt_add_cast_2;
    sumGain_fixpt_add_cast_3 = {sumGain_fixpt_add_temp_0[56], sumGain_fixpt_add_temp_0};
    sumGain_fixpt_cast_4 = {1'b0, sumGain_fixpt_tmp_1};
    sumGain_fixpt_mul_temp_1 = sumGain_fixpt_cast_4 * in3;
    if ((sumGain_fixpt_mul_temp_1[56] == 1'b0) && (sumGain_fixpt_mul_temp_1[55] != 1'b0)) begin
      sumGain_fixpt_add_cast_4 = 56'sh7FFFFFFFFFFFFF;
    end
    else if ((sumGain_fixpt_mul_temp_1[56] == 1'b1) && (sumGain_fixpt_mul_temp_1[55] != 1'b1)) begin
      sumGain_fixpt_add_cast_4 = 56'sh80000000000000;
    end
    else begin
      sumGain_fixpt_add_cast_4 = sumGain_fixpt_mul_temp_1[55:0];
    end
    sumGain_fixpt_add_cast_5 = {{2{sumGain_fixpt_add_cast_4[55]}}, sumGain_fixpt_add_cast_4};
    sumGain_fixpt_y1 = sumGain_fixpt_add_cast_3 + sumGain_fixpt_add_cast_5;
    //y = fi((y1/scaleVal), 1, 14, 13);
    if (sumGain_fixpt_y1 < 58'sh000000000000000) begin
      sumGain_fixpt_tmp_2 = 66'sh20000000000000000;
    end
    else begin
      sumGain_fixpt_tmp_2 = 66'sh1FFFFFFFFFFFFFFFF;
    end
    if (scaleVal == 8'b00000000) begin
    end
    else begin
      sumGain_fixpt_slice_cast = {1'b0, scaleVal};
      if (sumGain_fixpt_y1[57] == sumGain_fixpt_slice_cast[8]) begin
        sumGain_fixpt_y1_0 = 58'sh1FFFFFFFFFFFFFF;
      end
      else begin
        sumGain_fixpt_y1_0 = 58'sh200000000000000;
      end
      sumGain_fixpt_cast_5 = {1'b0, scaleVal};
      sumGain_fixpt_t_2 = {1'b0, scaleVal};
      if (sumGain_fixpt_t_2 == 31'sd0) begin
        sumGain_fixpt_div_temp_2 = sumGain_fixpt_y1_0;
      end
      else begin
        sumGain_fixpt_div_temp_2 = sumGain_fixpt_y1 / sumGain_fixpt_cast_5;
      end
      sumGain_fixpt_tmp_2 = {{8{sumGain_fixpt_div_temp_2[57]}}, sumGain_fixpt_div_temp_2};
    end
    //y = divide(numerictype(1, 14, 13), y1, scaleVal);
    if (((sumGain_fixpt_tmp_2[65] == 1'b0) && (sumGain_fixpt_tmp_2[64:37] != 28'b0000000000000000000000000000)) || ((sumGain_fixpt_tmp_2[65] == 1'b0) && (sumGain_fixpt_tmp_2[37:24] == 14'sb01111111111111))) begin
      y_1 = 14'sb01111111111111;
    end
    else if ((sumGain_fixpt_tmp_2[65] == 1'b1) && (sumGain_fixpt_tmp_2[64:37] != 28'b1111111111111111111111111111)) begin
      y_1 = 14'sb10000000000000;
    end
    else begin
      y_1 = sumGain_fixpt_tmp_2[37:24] + $signed({1'b0, sumGain_fixpt_tmp_2[23]});
    end
  end



  assign y = y_1;

endmodule  // sumGain_fixpt

