-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\iande\Desktop\covg_fpga\Matlab\scrapwork\codegen\IIRfilter\hdlsrc\IIRfilter_fixpt.vhd
-- Created: 2021-06-16 10:06:16
-- 
-- Generated by MATLAB 9.9, MATLAB Coder 5.1 and HDL Coder 3.17
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- y                             ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IIRfilter_fixpt
-- Source Path: IIRfilter_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IIRfilter_fixpt IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        x                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        ce_out                            :   OUT   std_logic;
        y                                 :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En8
        );
END IIRfilter_fixpt;


ARCHITECTURE rtl OF IIRfilter_fixpt IS

  -- Component Declarations
  COMPONENT Hd
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Hd_in                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          Hd_out                          :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Hd
    USE ENTITY work.Hd(rtl);

  -- Signals
  SIGNAL x_signed                         : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL s                                : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL y_tmp                            : std_logic_vector(13 DOWNTO 0);  -- ufix14

BEGIN
  u_Hd : Hd
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Hd_in => std_logic_vector(s),  -- sfix16_En15
              Hd_out => y_tmp  -- sfix14_En8
              );

  x_signed <= signed(x);

  
  s <= X"7FFF" WHEN (x_signed(15) = '0') AND (x_signed(14 DOWNTO 0) /= "000000000000000") ELSE
      X"8000" WHEN (x_signed(15) = '1') AND (x_signed(14 DOWNTO 0) /= "111111111111111") ELSE
      signed'(x_signed(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0');

  ce_out <= clk_enable;

  y <= y_tmp;

END rtl;

