%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.12 and Fixed-Point Designer 7.4           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [out] = matrix_mul_fixedpt_fixpt(A, B)
    % Lucas Koerner 
    % 2022/12/06
    % fixed point design of 2x2 * 2x1 matrix multiplication

    % inputs 
    % A,B

    fm = get_fimath();

    Am = fi(reshape(A,2,2), 1, 16, 15, fm);
    Bm = fi(reshape(B,2,1), 1, 16, 15, fm); % this is a Nx1 vector so reshape is uncessary 

    out = fi(Am*Bm, 1, 33, 30, fm);

end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
