set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:adc_pll} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:2 order:EARLY scoped_inst:{dac80508_gen[0].spi_fifo1/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:3 order:EARLY scoped_inst:{dac80508_gen[1].spi_fifo1/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:4 order:EARLY scoped_inst:{dac_ad5453_gen[0].spi_fifo0/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:5 order:EARLY scoped_inst:{dac_ad5453_gen[1].spi_fifo0/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:6 order:EARLY scoped_inst:{dac_ad5453_gen[2].spi_fifo0/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:7 order:EARLY scoped_inst:{dac_ad5453_gen[3].spi_fifo0/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:8 order:EARLY scoped_inst:{dac_ad5453_gen[4].spi_fifo0/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:9 order:EARLY scoped_inst:{dac_ad5453_gen[5].spi_fifo0/realTime_LPF_coeff_BRAM}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/fifo_w32_1024_r256_128/fifo_w32_1024_r256_128/fifo_w32_1024_r256_128_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/fifo_w32_1024_r256_128/fifo_w32_1024_r256_128/fifo_w32_1024_r256_128_in_context.xdc id:10 order:EARLY scoped_inst:fg_pipein_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024/fifo_w256_128_r32_1024_in_context.xdc id:11 order:EARLY scoped_inst:okPipeOut_fifo_ddr2} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/fifo_ADS8686/fifo_ADS8686/fifo_ADS8686_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/fifo_ADS8686/fifo_ADS8686/fifo_ADS8686_in_context.xdc id:12 order:EARLY scoped_inst:ads8686_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/ddr3_256_32/ddr3_256_32/ddr3_256_32_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/ddr3_256_32/ddr3_256_32/ddr3_256_32_in_context.xdc id:13 order:EARLY scoped_inst:u_ddr3_256_32} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:14 order:EARLY scoped_inst:{dac80508_gen[0].spi_fifo1/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:15 order:EARLY scoped_inst:{dac80508_gen[1].spi_fifo1/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:16 order:EARLY scoped_inst:{dac_ad5453_gen[0].spi_fifo0/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:17 order:EARLY scoped_inst:{dac_ad5453_gen[1].spi_fifo0/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:18 order:EARLY scoped_inst:{dac_ad5453_gen[2].spi_fifo0/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:19 order:EARLY scoped_inst:{dac_ad5453_gen[3].spi_fifo0/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:20 order:EARLY scoped_inst:{dac_ad5453_gen[4].spi_fifo0/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/mult_gen_0/mult_gen_0/mult_gen_0_in_context.xdc id:21 order:EARLY scoped_inst:{dac_ad5453_gen[5].spi_fifo0/u_Butterworth_0/mult1}} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/fifo_w128_512_r256_256/fifo_w128_512_r256_256/fifo_w128_512_r256_256_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/fifo_w128_512_r256_256/fifo_w128_512_r256_256/fifo_w128_512_r256_256_in_context.xdc id:22 order:EARLY scoped_inst:adc_to_ddr_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/fifo_w256_256_r128_512/fifo_w256_256_r128_512/fifo_w256_256_r128_512_in_context.xdc} rfile:../../../../../fpga_XEM7310.srcs/sources_1/ip/fifo_w256_256_r128_512/fifo_w256_256_r128_512/fifo_w256_256_r128_512_in_context.xdc id:23 order:EARLY scoped_inst:ddr_to_dac_fifo_ddr} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/constrs_1/xem7310.xdc} rfile:../../../../../fpga_XEM7310.srcs/constrs_1/xem7310.xdc id:24} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/stro4149/OneDrive - University of St. Thomas/Research Internship/Programs/covg_fpga/fpga_XEM7310/fpga_XEM7310.runs/synth_1/dont_touch.xdc} rfile:../../../dont_touch.xdc id:25} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../../../Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:26 order:LATE scoped_inst:okHI/core0/core0/a0/cb0/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name adc_pll/clk_out1 -source [get_pins adc_pll/clk_in1] -edges {1 2 3} -edge_shift {0.000 -0.500 -1.000} [get_pins adc_pll/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins adc_pll/clk_in1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells adc_pll]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac80508_gen[0].spi_fifo1/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac80508_gen[0].spi_fifo1/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac80508_gen[0].spi_fifo1/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac80508_gen[1].spi_fifo1/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac80508_gen[1].spi_fifo1/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac80508_gen[1].spi_fifo1/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[0].spi_fifo0/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[0].spi_fifo0/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[0].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[1].spi_fifo0/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[1].spi_fifo0/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[1].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[2].spi_fifo0/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[2].spi_fifo0/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[2].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[3].spi_fifo0/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[3].spi_fifo0/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[3].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[4].spi_fifo0/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[4].spi_fifo0/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[4].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[5].spi_fifo0/realTime_LPF_coeff_BRAM/clka}]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {dac_ad5453_gen[5].spi_fifo0/realTime_LPF_coeff_BRAM/clkb}]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[5].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins fg_pipein_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins fg_pipein_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fg_pipein_fifo]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins okPipeOut_fifo_ddr2/rd_clk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins okPipeOut_fifo_ddr2/wr_clk]
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells okPipeOut_fifo_ddr2]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins ads8686_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins ads8686_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ads8686_fifo]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name u_ddr3_256_32/ui_clk [get_pins u_ddr3_256_32/ui_clk]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:13 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:13 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:13 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:13 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:13 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:13 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:13 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:13 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:13 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[14]}]
set_property src_info {type:SCOPED_XDC file:13 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:13 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:13 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:13 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:13 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:13 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:13 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:13 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:13 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:13 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:13 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:13 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:13 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_cas_n]
set_property src_info {type:SCOPED_XDC file:13 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_cas_n]
set_property src_info {type:SCOPED_XDC file:13 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:13 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:13 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:13 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:13 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:13 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:13 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:13 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:13 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:13 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:13 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:13 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:13 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:13 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:13 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:13 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:13 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:13 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:13 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:13 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:13 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:13 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:13 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:13 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:13 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:13 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:13 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:13 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:13 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:13 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:13 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:13 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:13 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:13 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:13 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:13 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:13 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:13 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:13 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:13 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:13 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:13 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:13 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:13 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:13 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:13 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:13 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:13 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:13 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:13 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:13 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:13 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:13 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:13 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:13 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:13 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:13 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:13 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:13 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:13 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:13 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_ras_n]
set_property src_info {type:SCOPED_XDC file:13 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_ras_n]
set_property src_info {type:SCOPED_XDC file:13 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_reset_n]
set_property src_info {type:SCOPED_XDC file:13 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_reset_n]
set_property src_info {type:SCOPED_XDC file:13 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_we_n]
set_property src_info {type:SCOPED_XDC file:13 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_we_n]
set_property src_info {type:SCOPED_XDC file:13 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins u_ddr3_256_32/sys_clk_i]
set_property src_info {type:SCOPED_XDC file:13 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ddr3_256_32]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac80508_gen[0].spi_fifo1/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac80508_gen[0].spi_fifo1/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac80508_gen[1].spi_fifo1/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac80508_gen[1].spi_fifo1/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac_ad5453_gen[0].spi_fifo0/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[0].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac_ad5453_gen[1].spi_fifo0/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[1].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac_ad5453_gen[2].spi_fifo0/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[2].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac_ad5453_gen[3].spi_fifo0/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[3].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac_ad5453_gen[4].spi_fifo0/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[4].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins {dac_ad5453_gen[5].spi_fifo0/u_Butterworth_0/mult1/CLK}]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {dac_ad5453_gen[5].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:SCOPED_XDC file:22 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins adc_to_ddr_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins adc_to_ddr_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:22 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells adc_to_ddr_fifo]
set_property src_info {type:SCOPED_XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins ddr_to_dac_fifo_ddr/rd_clk]
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins ddr_to_dac_fifo_ddr/wr_clk]
set_property src_info {type:SCOPED_XDC file:23 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ddr_to_dac_fifo_ddr]
set_property src_info {type:XDC file:24 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {okHU[*]}]
set_property src_info {type:XDC file:24 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {okHU[*]}]
set_property src_info {type:XDC file:24 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {okUH[*]}]
set_property src_info {type:XDC file:24 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {okUHU[*]}]
set_property src_info {type:XDC file:24 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {okUHU[*]}]
set_property src_info {type:XDC file:24 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports okAA]
set_property src_info {type:XDC file:24 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 9.920 -name okUH0 [get_ports {okUH[0]}]
set_property src_info {type:XDC file:24 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks okUH0] -max -add_delay 8.000 [get_ports {okUH[*]}]
set_property src_info {type:XDC file:24 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks okUH0] -min -add_delay 10.000 [get_ports {okUH[*]}]
set_property src_info {type:XDC file:24 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -setup -from [get_ports {okUH[*]}] 2
set_property src_info {type:XDC file:24 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks okUH0] -max -add_delay 8.000 [get_ports {okUHU[*]}]
set_property src_info {type:XDC file:24 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks okUH0] -min -add_delay 2.000 [get_ports {okUHU[*]}]
set_property src_info {type:XDC file:24 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -setup -from [get_ports {okUHU[*]}] 2
set_property src_info {type:XDC file:24 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks okUH0] -max -add_delay 2.000 [get_ports {okHU[*]}]
set_property src_info {type:XDC file:24 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks okUH0] -min -add_delay -0.500 [get_ports {okHU[*]}]
set_property src_info {type:XDC file:24 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks okUH0] -max -add_delay 2.000 [get_ports {okUHU[*]}]
set_property src_info {type:XDC file:24 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks okUH0] -min -add_delay -0.500 [get_ports {okUHU[*]}]
set_property src_info {type:XDC file:24 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports sys_clkp]
set_property src_info {type:XDC file:24 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports sys_clkn]
set_property src_info {type:XDC file:24 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM FALSE [get_ports sys_clkp]
set_property src_info {type:XDC file:24 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name sys_clk [get_ports sys_clkp]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mmcm0_clkfb -source [get_pins okHI/mmcm0/CLKIN1] -multiply_by 1 -add -master_clock okUH0 [get_pins okHI/mmcm0/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mmcm0_clk0 -source [get_pins okHI/mmcm0/CLKIN1] -edges {1 2 3} -edge_shift {1.488 1.488 1.488} -add -master_clock okUH0 [get_pins okHI/mmcm0/CLKOUT0]
set_property src_info {type:XDC file:24 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks sys_clk] -group [get_clocks {mmcm0_clk0 okUH0}]
set_property src_info {type:XDC file:24 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name {ad7960_gen[0].adc7961/sclk_s} [get_ports {a_dco_p[0]}]
set_property src_info {type:XDC file:24 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name {ad7960_gen[1].adc7961/sclk_s} [get_ports {a_dco_p[1]}]
set_property src_info {type:XDC file:24 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name {ad7960_gen[2].adc7961/sclk_s} [get_ports {a_dco_p[2]}]
set_property src_info {type:XDC file:24 line:108 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name {ad7960_gen[3].adc7961/sclk_s} [get_ports {a_dco_p[3]}]
set_property src_info {type:XDC file:24 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports pushreset]
set_property src_info {type:XDC file:24 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_p[3]}]
set_property src_info {type:XDC file:24 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_p[3]}]
set_property src_info {type:XDC file:24 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_n[3]}]
set_property src_info {type:XDC file:24 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_n[3]}]
set_property src_info {type:XDC file:24 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_p[3]}]
set_property src_info {type:XDC file:24 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_p[3]}]
set_property src_info {type:XDC file:24 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_p[2]}]
set_property src_info {type:XDC file:24 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_n[3]}]
set_property src_info {type:XDC file:24 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_n[3]}]
set_property src_info {type:XDC file:24 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_n[2]}]
set_property src_info {type:XDC file:24 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_p[3]}]
set_property src_info {type:XDC file:24 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_p[1]}]
set_property src_info {type:XDC file:24 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_n[3]}]
set_property src_info {type:XDC file:24 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_n[1]}]
set_property src_info {type:XDC file:24 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_p[3]}]
set_property src_info {type:XDC file:24 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_p[3]}]
set_property src_info {type:XDC file:24 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_p[2]}]
set_property src_info {type:XDC file:24 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_n[3]}]
set_property src_info {type:XDC file:24 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_n[3]}]
set_property src_info {type:XDC file:24 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_n[2]}]
set_property src_info {type:XDC file:24 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_p[2]}]
set_property src_info {type:XDC file:24 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_p[2]}]
set_property src_info {type:XDC file:24 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_p[2]}]
set_property src_info {type:XDC file:24 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_p[2]}]
set_property src_info {type:XDC file:24 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_n[2]}]
set_property src_info {type:XDC file:24 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_n[2]}]
set_property src_info {type:XDC file:24 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_n[2]}]
set_property src_info {type:XDC file:24 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_n[2]}]
set_property src_info {type:XDC file:24 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_p[2]}]
set_property src_info {type:XDC file:24 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_p[0]}]
set_property src_info {type:XDC file:24 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_p[0]}]
set_property src_info {type:XDC file:24 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_n[2]}]
set_property src_info {type:XDC file:24 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_n[0]}]
set_property src_info {type:XDC file:24 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_n[0]}]
set_property src_info {type:XDC file:24 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_p[0]}]
set_property src_info {type:XDC file:24 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_p[0]}]
set_property src_info {type:XDC file:24 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_n[0]}]
set_property src_info {type:XDC file:24 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {gp_lvds_n[0]}]
set_property src_info {type:XDC file:24 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_p[0]}]
set_property src_info {type:XDC file:24 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_p[0]}]
set_property src_info {type:XDC file:24 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en0_hv[0]}]
set_property src_info {type:XDC file:24 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_n[0]}]
set_property src_info {type:XDC file:24 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_n[0]}]
set_property src_info {type:XDC file:24 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en0_hv[1]}]
set_property src_info {type:XDC file:24 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_p[0]}]
set_property src_info {type:XDC file:24 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en0_hv[2]}]
set_property src_info {type:XDC file:24 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_n[0]}]
set_property src_info {type:XDC file:24 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en0_hv[3]}]
set_property src_info {type:XDC file:24 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_p[1]}]
set_property src_info {type:XDC file:24 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en_hv[0]}]
set_property src_info {type:XDC file:24 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_cnv_n[1]}]
set_property src_info {type:XDC file:24 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en_hv[1]}]
set_property src_info {type:XDC file:24 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_p[1]}]
set_property src_info {type:XDC file:24 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_p[1]}]
set_property src_info {type:XDC file:24 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {a_en_hv[2]}]
set_property src_info {type:XDC file:24 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_d_n[1]}]
set_property src_info {type:XDC file:24 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_d_n[1]}]
set_property src_info {type:XDC file:24 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_p[1]}]
set_property src_info {type:XDC file:24 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_clk_n[1]}]
set_property src_info {type:XDC file:24 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {up[0]}]
set_property src_info {type:XDC file:24 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dn[4]}]
set_property src_info {type:XDC file:24 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {up[1]}]
set_property src_info {type:XDC file:24 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dn[3]}]
set_property src_info {type:XDC file:24 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {up[2]}]
set_property src_info {type:XDC file:24 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dn[2]}]
set_property src_info {type:XDC file:24 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {up[3]}]
set_property src_info {type:XDC file:24 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dn[1]}]
set_property src_info {type:XDC file:24 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {up[4]}]
set_property src_info {type:XDC file:24 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dn[0]}]
set_property src_info {type:XDC file:24 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {up[5]}]
set_property src_info {type:XDC file:24 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_p[1]}]
set_property src_info {type:XDC file:24 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_p[1]}]
set_property src_info {type:XDC file:24 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {a_dco_n[1]}]
set_property src_info {type:XDC file:24 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {a_dco_n[1]}]
set_property src_info {type:XDC file:24 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_resetb]
set_property src_info {type:XDC file:24 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_csb[5]}]
set_property src_info {type:XDC file:24 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_sclk]
set_property src_info {type:XDC file:24 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sdi[5]}]
set_property src_info {type:XDC file:24 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_sdoa]
set_property src_info {type:XDC file:24 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sclk[5]}]
set_property src_info {type:XDC file:24 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_sdi]
set_property src_info {type:XDC file:24 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_csb[4]}]
set_property src_info {type:XDC file:24 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_sdob]
set_property src_info {type:XDC file:24 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sdi[4]}]
set_property src_info {type:XDC file:24 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_csb]
set_property src_info {type:XDC file:24 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sclk[4]}]
set_property src_info {type:XDC file:24 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_convst]
set_property src_info {type:XDC file:24 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_csb[3]}]
set_property src_info {type:XDC file:24 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ads_busy]
set_property src_info {type:XDC file:24 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sdi[3]}]
set_property src_info {type:XDC file:24 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_sdo[0]}]
set_property src_info {type:XDC file:24 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sclk[3]}]
set_property src_info {type:XDC file:24 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_sclk[0]}]
set_property src_info {type:XDC file:24 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_csb[2]}]
set_property src_info {type:XDC file:24 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_csb[0]}]
set_property src_info {type:XDC file:24 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sdi[2]}]
set_property src_info {type:XDC file:24 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_sdi[0]}]
set_property src_info {type:XDC file:24 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sclk[2]}]
set_property src_info {type:XDC file:24 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_sdo[1]}]
set_property src_info {type:XDC file:24 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_csb[0]}]
set_property src_info {type:XDC file:24 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_sclk[1]}]
set_property src_info {type:XDC file:24 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sdi[0]}]
set_property src_info {type:XDC file:24 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_csb[1]}]
set_property src_info {type:XDC file:24 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sclk[0]}]
set_property src_info {type:XDC file:24 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ds_sdi[1]}]
set_property src_info {type:XDC file:24 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_csb[1]}]
set_property src_info {type:XDC file:24 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports en_5v]
set_property src_info {type:XDC file:24 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sdi[1]}]
set_property src_info {type:XDC file:24 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports en_3v3]
set_property src_info {type:XDC file:24 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {d_sclk[1]}]
set_property src_info {type:XDC file:24 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports en_1v8]
set_property src_info {type:XDC file:24 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[2]}]
set_property src_info {type:XDC file:24 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports en_15v]
set_property src_info {type:XDC file:24 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[1]}]
set_property src_info {type:XDC file:24 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports en_n15v]
set_property src_info {type:XDC file:24 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[3]}]
set_property src_info {type:XDC file:24 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dn[5]}]
set_property src_info {type:XDC file:24 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ls_sda]
set_property src_info {type:XDC file:24 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ls_scl]
set_property src_info {type:XDC file:24 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports qw_sda]
set_property src_info {type:XDC file:24 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports qw_scl]
set_property src_info {type:XDC file:24 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_scl[0]}]
set_property src_info {type:XDC file:24 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_sda[0]}]
set_property src_info {type:XDC file:24 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_scl[1]}]
set_property src_info {type:XDC file:24 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_sda[1]}]
set_property src_info {type:XDC file:24 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_scl[2]}]
set_property src_info {type:XDC file:24 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_sda[2]}]
set_property src_info {type:XDC file:24 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_scl[3]}]
set_property src_info {type:XDC file:24 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dc_sda[3]}]
set_property src_info {type:XDC file:24 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {en_ipump[0]}]
set_property src_info {type:XDC file:24 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[0]}]
set_property src_info {type:XDC file:24 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {en_ipump[1]}]
set_property src_info {type:XDC file:24 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sma[0]}]
set_property src_info {type:XDC file:24 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sma[1]}]
set_property src_info {type:XDC file:24 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {led[*]}]
set_property src_info {type:XDC file:24 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[*]}]
set_property src_info {type:XDC file:24 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[*]}]
set_property src_info {type:XDC file:24 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[*]}]
set_property src_info {type:XDC file:24 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[*]}]
set_property src_info {type:XDC file:24 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[*]}]
set_property src_info {type:XDC file:24 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[*]}]
set_property src_info {type:XDC file:24 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:24 line:723 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:24 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:24 line:727 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:24 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_we_n]
set_property src_info {type:XDC file:24 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property src_info {type:XDC file:24 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:24 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:24 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cke[*]}]
set_property src_info {type:XDC file:24 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[*]}]
set_property src_info {type:XDC file:24 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_odt[*]}]
set_property src_info {type:XDC file:24 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[*]}]
set_property src_info {type:XDC file:24 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[*]}]
set_property src_info {type:XDC file:24 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[*]}]
set_property src_info {type:XDC file:24 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_dqs*]
set_property src_info {type:XDC file:24 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_dqs*]
set_property src_info {type:XDC file:24 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports ddr3_ck*]
set_property src_info {type:XDC file:24 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_*]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells adc_pll]
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins okHI/core0/core0/a0/cb0/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst/src_arst] -to [get_cells [list {okHI/core0/core0/a0/cb0/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst/arststages_ff_reg[0]} {okHI/core0/core0/a0/cb0/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst/arststages_ff_reg[1]}]]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac80508_gen[0].spi_fifo1/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac80508_gen[1].spi_fifo1/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[0].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[1].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[2].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[3].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[4].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[5].spi_fifo0/realTime_LPF_coeff_BRAM}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells fg_pipein_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells okPipeOut_fifo_ddr2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ads8686_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_ddr3_256_32]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac80508_gen[0].spi_fifo1/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac80508_gen[1].spi_fifo1/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[0].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[1].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[2].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[3].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[4].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {dac_ad5453_gen[5].spi_fifo0/u_Butterworth_0/mult1}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells adc_to_ddr_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ddr_to_dac_fifo_ddr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells okHI/core0/core0/a0/cb0/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst]
