# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: xem7310.xdc

# IP: ip/mult_gen_2/mult_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_2 || ORIG_REF_NAME==mult_gen_2} -quiet] -quiet
