# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1.xci
# IP: The module: 'clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1.xci
# IP: The module: 'clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/koer2434/Documents/fpga/covg_fpga/fpga_XEM7310/fpga_XEM7310.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
