// -------------------------------------------------------------
// 
// File Name: /Users/koer2434/Documents/covg_fpga/Matlab/control_system/observer/observer/codegen/observer/hdlsrc/observer_fixpt_tc.v
// Created: 2022-12-13 15:48:19
// 
// Generated by MATLAB 9.12, MATLAB Coder 5.4 and HDL Coder 3.20
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: observer_fixpt_tc
// Source Path: observer_fixpt_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb_40_1_0  : identical to clk_enable
// enb         : 40x slower than clk with last phase
// enb_1_1_1   : 40x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module observer_fixpt_tc
          (clk,
           reset,
           clk_enable,
           enb_40_1_0,
           enb,
           enb_1_1_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb_40_1_0;
  output  enb;
  output  enb_1_1_1;


  reg [5:0] count40;  // ufix6
  wire phase_all;
  reg  phase_0;
  wire phase_0_tmp;
  reg  phase_1;
  wire phase_1_tmp;


  always @ (posedge clk or posedge reset)
    begin: Counter40
      if (reset == 1'b1) begin
        count40 <= 6'b000001;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (count40 >= 6'b100111) begin
            count40 <= 6'b000000;
          end
          else begin
            count40 <= count40 + 6'b000001;
          end
        end
      end
    end // Counter40

  assign phase_all = clk_enable ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end // temp_process1

  assign  phase_0_tmp = (count40 == 6'b100111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end // temp_process2

  assign  phase_1_tmp = (count40 == 6'b000000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign enb_40_1_0 =  phase_all & clk_enable;

  assign enb =  phase_0 & clk_enable;

  assign enb_1_1_1 =  phase_1 & clk_enable;


endmodule  // observer_fixpt_tc

