function y = HammingWindowFIR(x)
%HAMMINGWINDOWFIR Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 30-Jul-2021 09:55:49

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % Numerator coefficient vector
    Numerator = [0.0068937 0.011519 0.024437 0.045017 0.070404 0.096086 ...
        0.11697 0.12867 0.12867 0.11697 0.096086 0.070404 ...
        0.045017 0.024437 0.011519 0.0068937];
    
    Hd = dsp.FIRFilter( ...
        'Numerator', Numerator, ...
        'CoefficientsDataType', 'Custom', ...
        'CustomCoefficientsDataType', numerictype(true,32,33));
end

s = fi(x,1,32,31,'RoundingMethod','Round','OverflowAction','Saturate');
y = step(Hd,s);


% [EOF]
end