function filter_generatehdl(filtobj)
%  FILTER_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 9.9 and Filter Design HDL Coder 3.1.8.
%  Generated on: 2021-06-18 13:00:13
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  ResetType: Synchronous
%  TargetDirectory: C:\Users\iande\Desktop\covg_fpga\Matlab\scrapwork\IIRcodegen
%  CoefficientSource: ProcessorInterface
%  TargetLanguage: Verilog
%  TestBenchStimulus: step ramp chirp 
%  ClockHighTime: 2.5
%  ClockLowTime: 2.5
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time IIR Filter (real)
%  -------------------------------
%  Filter Structure    : Direct-Form II, Second-Order Sections
%  Number of Sections  : 3
%  Stable              : Yes
%  Linear Phase        : No
%  Arithmetic          : fixed
%  Numerator           : s16,13 -> [-4 4)
%  Denominator         : s16,14 -> [-2 2)
%  Scale Values        : s16,17 -> [-2.500000e-01 2.500000e-01)
%  Input               : s16,0 -> [-32768 32768)
%  Section Input       : s16,11 -> [-16 16)
%  Section Output      : s16,10 -> [-32 32)
%  Output              : s14,8 -> [-32 32)
%  State               : s16,15 -> [-1 1)
%  Numerator Prod      : s32,28 -> [-8 8)
%  Denominator Prod    : s32,29 -> [-4 4)
%  Numerator Accum     : s34,28 -> [-32 32)
%  Denominator Accum   : s34,29 -> [-16 16)
%  Round Mode          : convergent
%  Overflow Mode       : wrap

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'ResetType', 'Synchronous',... 
               'TargetDirectory', 'C:\Users\iande\Desktop\covg_fpga\Matlab\scrapwork\IIRcodegen',... 
               'CoefficientSource', 'ProcessorInterface',... 
               'TargetLanguage', 'Verilog',... 
               'TestBenchStimulus',  {'step', 'ramp', 'chirp'},... 
               'ClockHighTime', 2.5,... 
               'ClockLowTime', 2.5,... 
               'GenerateHDLTestbench', 'on');

% [EOF]
