function y = LeastSquaresFIR_doublePrecision.fda(x)
%LEASTSQUARESFIR_DOUBLEPRECISION.FDA Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 01-Jul-2021 11:43:03

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR least-squares Lowpass filter designed using the FIRLS function.
    %
    % % All frequency values are in Hz.
    % Fs = 5000000;  % Sampling Frequency
    %
    % N     = 10;      % Order
    % Fpass = 500000;  % Passband Frequency
    % Fstop = 600000;  % Stopband Frequency
    % Wpass = 1;       % Passband Weight
    % Wstop = 10;      % Stopband Weight
    %
    % % Calculate the coefficients using the FIRLS function.
    % b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.0250158421185262 0.0618132125350809 ...
        0.105552495617917 0.147314425008783 0.177403242985933 0.18836379727887 ...
        0.177403242985933 0.147314425008783 0.105552495617917 0.0618132125350809 ...
        0.0250158421185262]);
end

y = step(Hd,double(x));


% [EOF]
end