function y = ThirdOrderButter(x)
%THIRDORDERBUTTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 24-Jun-2021 13:42:17

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    Denominator = [1 -2.6466 2.3529 -0.70166];  % Denominator coefficient
    % vector
    
    % Numerator coefficient vector
    Numerator   = [0.0005844 0.0017532 0.0017532 0.0005844];
    
    Hd = dsp.IIRFilter( ...
        'Structure', 'Direct form I', ...
        'Numerator', Numerator, ...
        'Denominator', Denominator, ...
        'NumeratorCoefficientsDataType', 'Custom', ...
        'CustomNumeratorCoefficientsDataType', numerictype([],16,24), ...
        'DenominatorCoefficientsDataType', 'Custom', ...
        'CustomDenominatorCoefficientsDataType', numerictype([],16,13), ...
        'OutputDataType', 'Custom', ...
        'CustomOutputDataType', numerictype([],14,8), ...
        'RoundingMethod', 'Convergent');
end

s = fi(x,1,16,0,'RoundingMethod','Round','OverflowAction','Saturate');
y = step(Hd,s);


% [EOF]
end