%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.9 and Fixed-Point Designer 7.1           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function y = sumGain_wrapper_fixpt(in1,in2,in3,g1,g2,g3,scaleVal)
    fm = get_fimath();
    in1_in = in1;
    in2_in = in2;
    in3_in = in3;
    g1_in = g1;
    g2_in = g2;
    g3_in = g3;
    scaleVal_in = scaleVal;
    [y_out] = sumGain_fixpt( in1_in, in2_in, in3_in, g1_in, g2_in, g3_in, scaleVal_in );
    y = y_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
