%% DSP Filter
%% Input
Fs = 5e6;            % Sampling frequency                    
T = 1/Fs;             % Sampling period       
L = 100;             % Length of signal
t = (0:L-1)*T;        % Time vector

j = 4.096*(t>1e-5);
%j = (4.096*(t>1e-5))-(4.096/2);
%j = 4.096*((0.5e-5<t)&(t<1.5e-5));
%F = fft(j);

codes = int16.empty;
figure(1);
for x = (1:L)
    if (j(x)/4.096)>0
        code = int16((j(x)/4.096)*(2^15-1));
        %code = fi((j(x)/4.096)*(2^15-1));
    elseif (j(x)/4.096)<0
        code = int16((j(x)/4.096)*(2^15));
        %code = fi((j(x)/4.096)*(2^15));
    else
        code = int16(0);
        %code = fi(0);
    end
    codes = [codes; code];
    out = IIRfilter(code);
    plot(t(x), out*2^8, '*');
    hold on;
end

figure(2);
subplot(1,3,1);
plot(t,j);
subplot(1,3,2);
plot(t, codes);
subplot(1,3,3);
plot(t, fi(codes));

%%
figure(3);
out = doFilter(codes);
subplot(2,2,1);
plot(t,codes);
title('Original Signal');
xlabel('t[s]');
ylabel('Amplitude');

subplot(2,2,2);
plot(t, out);
title('Filtered Signal (Filter Builder - FIR)');
xlabel('t[s]');
ylabel('Amplitude');

subplot(2,2,3);
out2 = FIRfilter(codes);
plot(t, out2);
title('Filtered Signal (Filter Designer - FIR)');
xlabel('t[s]');
ylabel('Amplitude');

subplot(2,2,4);
out3 =IIRfilter(codes);
plot(t, out3);
title('Filtered Signal (Filter Designer - IIR)');
xlabel('t[s]');
ylabel('Amplitude');

% figure(4);
% %subplot(3,2,4);
% out4 =IIR(codes);
% plot(t, out4);
% title('Filtered Signal (Filter Builder - IIR)');
% xlabel('t[s]');
% ylabel('Amplitude');






%% DSP Filter function
function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 14-Jun-2021 14:45:45

persistent Hd;

if isempty(Hd)
    
    Fpass = 300000;   % Passband Frequency
    Fstop = 476800;   % Stopband Frequency
    Apass = 1;        % Passband Ripple (dB)
    Astop = 20;       % Stopband Attenuation (dB)
    Fs    = 5000000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'ifir');
    
    set(Hd.Stage(1), 'Arithmetic', 'fixed', ...
        'InputWordLength', 16, ...
        'InputFracLength', 0, ...
        'CoeffWordLength', 16, ...
        'CoeffAutoScale', true, ...
        'FilterInternals', 'Fullprecision');
    set(Hd.Stage(2), 'Arithmetic', 'fixed', ...
        'InputWordLength', 16, ...
        'InputFracLength', 0, ...
        'CoeffWordLength', 16, ...
        'CoeffAutoScale', true, ...
        'FilterInternals', 'Fullprecision');
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);
end
%% FIR filter (filter designer)
function y = FIRfilter(x)
%FIRFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 15-Jun-2021 09:57:17

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

% The following code was used to design the filter coefficients:
% % Interpolated FIR Lowpass filter designed using the IFIR function.
%
% % All frequency values are in Hz.
% Fs = 5000000;  % Sampling Frequency
%
% Fpass = 200000;          % Passband Frequency
% Fstop = 476800;          % Stopband Frequency
% Dpass = 0.057501127785;  % Passband Ripple
% Dstop = 0.1;             % Stopband Attenuation
% L     = 4;               % Interpolation Factor
%
% % Calculate the coefficients using the IFIR function.
% [h, g] = ifir(L, 'low', [Fpass Fstop]/(Fs/2), [Dpass Dstop]);


%% Construction
persistent filter1 filter2
if isempty(filter1)
    filter1 = dsp.FIRFilter(  ...
        'Numerator', [-0.07502182644916526 0 0 0 0.080795018473145214 0 0 0 ...
        0.48502135547034186 0 0 0 0.48502135547034186 0 0 0 0.080795018473145214 ...
        0 0 0 -0.07502182644916526]);
    filter2 = dsp.FIRFilter(  ...
        'Numerator', [-0.038541944347873509 -0.0070793099742488558 ...
        0.026205668845601996 0.081486429744326239 0.14460708478219247 ...
        0.1949004698410795 0.2140890789562408 0.1949004698410795 ...
        0.14460708478219247 0.081486429744326239 0.026205668845601996 ...
        -0.0070793099742488558 -0.038541944347873509]);
end


%% Process
y1 = filter1( x );
y  = filter2( y1);




% [EOF]
end

%% IIR filter

function y = IIRfilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 15-Jun-2021 12:26:08

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 200000;   % Passband Frequency
    % Fstop = 400000;   % Stopband Frequency
    % Apass = 1;        % Passband Ripple (dB)
    % Astop = 20;       % Stopband Attenuation (dB)
    % Fs    = 5000000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.72868912225509 0.822065283793064; 1 2 1 1 ...
        -1.51115501871521 0.592780947472364; 1 1 0 1 -0.720925717959358 0], ...
        'ScaleValues', [0.0233440403844928; 0.0204064821892894; ...
        0.139537141020321; 1], ...
        'SectionInputDataType', 'Custom', ...
        'CustomSectionInputDataType', numerictype([],16,11), ...
        'SectionOutputDataType', 'Custom', ...
        'CustomSectionOutputDataType', numerictype([],16,10), ...
        'NumeratorCoefficientsDataType', 'Custom', ...
        'CustomNumeratorCoefficientsDataType', numerictype([],16,13), ...
        'DenominatorCoefficientsDataType', 'Custom', ...
        'CustomDenominatorCoefficientsDataType', numerictype([],16,14), ...
        'ScaleValuesDataType', 'Custom', ...
        'CustomScaleValuesDataType', numerictype([],16,17), ...
        'NumeratorProductDataType', 'Custom', ...
        'CustomNumeratorProductDataType', numerictype([],32,28), ...
        'DenominatorProductDataType', 'Custom', ...
        'CustomDenominatorProductDataType', numerictype([],32,29), ...
        'NumeratorAccumulatorDataType', 'Custom', ...
        'CustomNumeratorAccumulatorDataType', numerictype([],34,28), ...
        'DenominatorAccumulatorDataType', 'Custom', ...
        'CustomDenominatorAccumulatorDataType', numerictype([],34,29), ...
        'StateDataType', 'Custom', ...
        'CustomStateDataType', numerictype([],16,15), ...
        'OutputDataType', 'Custom', ...
        'CustomOutputDataType', numerictype([],14,8), ...
        'RoundingMethod', 'Convergent');
end

s = fi(x,1,16,15,'RoundingMethod', 'Round', 'OverflowAction', 'Saturate');
y = step(Hd,s);
end

%%

function y = IIR(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 15-Jun-2021 12:34:07

persistent Hd;

if isempty(Hd)
    
    Fpass = 200000;   % Passband Frequency
    Fstop = 400000;   % Stopband Frequency
    Apass = 1;        % Passband Ripple (dB)
    Astop = 20;       % Stopband Attenuation (dB)
    Fs    = 5000000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    set(Hd, 'Arithmetic', 'fixed', ...
        'InputWordLength', 16, ...
        'InputFracLength', 0, ...
        'CoeffWordLength', 16, ...
        'CoeffAutoScale', true, ...
        'SectionInputWordLength', 16, ...
        'SectionInputAutoScale', true, ...
        'SectionOutputWordLength', 16, ...
        'SectionOutputAutoScale', true, ...
        'StateWordLength', 16, ...
        'StateFracLength', 15, ...
        'ProductMode', 'Fullprecision', ...
        'AccumMode', 'KeepMSB', ...
        'AccumWordLength', 40, ...
        'CastBeforeSum', true, ...
        'OutputWordLength', 14, ...
        'OutputMode', 'Avoidoverflow', ...
        'RoundMode', 'convergent', ...
        'OverflowMode', 'wrap');
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);
end
