function y = untitled(x)
%UNTITLED Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 18-Jun-2021 10:26:16

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Lowpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 5000000;  % Sampling Frequency
    %
    % Fpass = 2000000;         % Passband Frequency
    % Fstop = 2200000;         % Stopband Frequency
    % Dpass = 0.057501127785;  % Passband Ripple
    % Dstop = 0.1;             % Stopband Attenuation
    % flag  = 'scale';         % Sampling Flag
    %
    % % Calculate the order from the parameters using KAISERORD.
    % [N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.0135658392118067 -0.0110369361877611 ...
        0.0045330525287601 0.0051316859686713 -0.0160334023969418 ...
        0.0253909514066539 -0.0300771927846966 0.0272949946930884 ...
        -0.0152716026738102 -0.00619429301025544 0.035477253442543 ...
        -0.0692470239169807 0.102969175157867 -0.131696801864467 ...
        0.150993453633893 0.82840169358326 0.150993453633893 -0.131696801864467 ...
        0.102969175157867 -0.0692470239169807 0.035477253442543 ...
        -0.00619429301025544 -0.0152716026738102 0.0272949946930884 ...
        -0.0300771927846966 0.0253909514066539 -0.0160334023969418 ...
        0.0051316859686713 0.0045330525287601 -0.0110369361877611 ...
        0.0135658392118067]);
end

y = step(Hd,double(x));


% [EOF]
