%% DSP Filter
%% Generate SOS Matrix
fc = 500e3;
fs = 5e6;
order = 4;
StopbandAttenuation = 40;
PassbandRipple = 1;

[z, p, k] = ellip(order, PassbandRipple, StopbandAttenuation, fc/(fs/2));

[sos, g] = zp2sos(z, p, k);
sos1 = zp2sos(z, p, k);
figure(1);
freqz(sos1, 512, fs);
%% Input
Fs = 5e6;            % Sampling frequency                    
T = 1/Fs;             % Sampling period       
L = 200;             % Length of signal
%fsine = 10000;        % frequency of test sinewave
%L = round(((1/fsine)/T))*5;
t = (0:L-1)*T;        % Time vector

O = numerictype([],16,0);
j = 4.096*(t>1e-5);
%j = 4.096*sin(2*pi*fsine*t);
%j = sin(2*pi*300000*t) + sin(2*pi*700000*t);

codes = fi('numerictype', O);
m = numerictype([], 14, 8);
output = fi('numerictype', m);
figure(2);
%loop that takes the input step function and outputs the hex codes that the
%AD7961 would output
for x = (1:L)
    if (j(x)/4.096)>0
        code = fi((j(x)/4.096)*(2^15-1), 'numerictype', O);
    elseif (j(x)/4.096)<0
        code = fi((j(x)/4.096)*(2^15), 'numerictype', O);
    else
        code = fi(0, 'numerictype', O);
    end
    codes = [codes; code];
    %out = doFilter(code);
    out = EllipticFilterFunction(code*2^-15, sos, g);
    output = [output, out];
    plot(t(x), out, '*');
    hold on;
end

% Plotting Input and Output on same graph
plot(t, codes*2^-15);%normalized the step function here to be able to view both filter output and step voltage
title('Original Signal and Step Response of IIR LP filter');
xlabel('t[s]');
ylabel('Amplitude');

%% Amplitude Spectrum of input/output

Y = fft(double(codes*2^-15));
Y2 = fft(double(output));

P2 = abs(Y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2*P1(2:end-1);

P4 = abs(Y2/L);
P3 = P4(1:L/2+1);
P3(2:end-1) = 2*P3(2:end-1);

f = Fs*(0:(L/2))/L;

figure(3);
subplot(2, 1, 1);
stem(f,P1);
title('Single-Sided Amplitude Spectrum of X(t)');
xlabel('f (Hz)');
ylabel('|P1(f)|');

subplot(2, 1, 2);
stem(f,P3); 
title('Single-Sided Amplitude Spectrum of X(t)');
xlabel('f (Hz)');
ylabel('|P1(f)|');

%% Plotting Group Delay
figure(4);
grpdelay(sos, 512, fs);
title('Group Delay');

%% Plotting Phase Delay
figure(5);
phasedelay(sos, 512, fs);
title('Phase Delay');

%% Step Response
figure(6);
stepz(sos1, 50, fs)
grid

% step response info/measurements
[h, t] = stepz(sos1, 50, fs);
S = stepinfo(h, t);
disp(S);

%% Reference Elliptic

function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 28-Jun-2021 13:18:47

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 4;        % Order
    % Fpass = 500000;   % Passband Frequency
    % Apass = 1;        % Passband Ripple (dB)
    % Astop = 20;       % Stopband Attenuation (dB)
    % Fs    = 5000000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,fp,ap,ast', N, Fpass, Apass, Astop, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'FilterStructure', 'df2tsos', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'SOSMatrix', [1 -0.779784979298711 1 1 -1.41986169759184 ...
        0.606410994194448; 1 -1.529043270275 1 1 -1.56709478795528 ...
        0.941167169250548], ...
        'ScaleValues', [0.775240515358746; 0.139603216201067; 1], ...
        'SectionInputDataType', 'Custom', ...
        'CustomSectionInputDataType', numerictype([],16,15), ...
        'SectionOutputDataType', 'Custom', ...
        'CustomSectionOutputDataType', numerictype([],16,14), ...
        'NumeratorCoefficientsDataType', 'Custom', ...
        'CustomNumeratorCoefficientsDataType', numerictype([],16,13), ...
        'DenominatorCoefficientsDataType', 'Custom', ...
        'CustomDenominatorCoefficientsDataType', numerictype([],16,13), ...
        'ScaleValuesDataType', 'Custom', ...
        'CustomScaleValuesDataType', numerictype([],16,17), ...
        'NumeratorProductDataType', 'Custom', ...
        'CustomNumeratorProductDataType', numerictype([],32,29), ...
        'DenominatorProductDataType', 'Custom', ...
        'CustomDenominatorProductDataType', numerictype([],32,29), ...
        'NumeratorAccumulatorDataType', 'Custom', ...
        'CustomNumeratorAccumulatorDataType', numerictype([],34,29), ...
        'DenominatorAccumulatorDataType', 'Custom', ...
        'CustomDenominatorAccumulatorDataType', numerictype([],34,29), ...
        'StateDataType', 'Custom', ...
        'CustomStateDataType', numerictype([],16,11), ...
        'OutputDataType', 'Custom', ...
        'CustomOutputDataType', numerictype([],14,9), ...
        'RoundingMethod', 'Convergent');
end

s = fi(x,1,16,15,'RoundingMethod', 'Round', 'OverflowAction', 'Saturate');
y = step(Hd,s);

end
%% Elliptic Filter

function y = EllipticFilterFunction(x, sos, g)
%ELLIPTICFILTERFUNCTION Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 28-Jun-2021 13:41:46

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    Gain       = g;  % Gain coefficient vector
    
    % SOS_Matrix coefficient vector
    SOS_Matrix = sos;
    
    Hd = dsp.BiquadFilter( ...
        'SOSMatrix', SOS_Matrix, ...
        'ScaleValues', Gain, ...
        'SectionInputDataType', 'Custom', ...
        'CustomSectionInputDataType', numerictype([],16,15), ...
        'SectionOutputDataType', 'Custom', ...
        'CustomSectionOutputDataType', numerictype([],16,14), ...
        'NumeratorCoefficientsDataType', 'Custom', ...
        'CustomNumeratorCoefficientsDataType', numerictype([],32,30), ...
        'DenominatorCoefficientsDataType', 'Custom', ...
        'CustomDenominatorCoefficientsDataType', numerictype([],32,30), ...
        'ScaleValuesDataType', 'Custom', ...
        'CustomScaleValuesDataType', numerictype([],32,31), ...
        'NumeratorProductDataType', 'Custom', ...
        'CustomNumeratorProductDataType', numerictype([],48,45), ...
        'DenominatorProductDataType', 'Custom', ...
        'CustomDenominatorProductDataType', numerictype([],48,45), ...
        'NumeratorAccumulatorDataType', 'Custom', ...
        'CustomNumeratorAccumulatorDataType', numerictype([],50,45), ...
        'DenominatorAccumulatorDataType', 'Custom', ...
        'CustomDenominatorAccumulatorDataType', numerictype([],50,45), ...
        'StateDataType', 'Custom', ...
        'CustomStateDataType', numerictype([],16,11), ...
        'OutputDataType', 'Custom', ...
        'CustomOutputDataType', numerictype([],14,8), ...
        'RoundingMethod', 'Convergent');
end

% s = fi(x,1,16,15,'RoundingMethod', 'Round', 'OverflowAction', 'Saturate');
% y = step(Hd,s);
y = Hd(x);


% [EOF]
end